import prisma from '../prisma';

export interface GeneratedQuodom {
  title: string;
  items: Array<{ productId: number; quantity: number }>;
}

export async function generateQuodomFromPrompt(prompt: string, userId: string): Promise<GeneratedQuodom> {
  const geminiApiKey = process.env.GEMINI_API_KEY;
  const openaiApiKey = process.env.OPENAI_API_KEY;

  const hasApiKey = (geminiApiKey && geminiApiKey.trim() !== '') || (openaiApiKey && openaiApiKey.trim() !== '');

  if (!hasApiKey) {
    console.log('No API key configured (GEMINI_API_KEY / OPENAI_API_KEY). Running local mock fallback.');
    return generateMockQuodom(prompt);
  }

  try {
    // 1. Fetch catalog
    const products = await prisma.product.findMany({
      include: {
        category: true
      }
    });

    if (products.length === 0) {
      console.warn('Database catalog is empty. Falling back to mock generator.');
      return generateMockQuodom(prompt);
    }

    const validProductIds = new Set(products.map(p => p.id));

    // 2. Format catalog for LLM (very compact to avoid token waste)
    const catalogString = products.map(p => 
      `ID:${p.id}|Name:${p.name}|Category:${p.category.name}|Unit:${p.unit}${p.description ? `|Desc:${p.description}` : ''}`
    ).join('\n');

    const systemPrompt = `You are the AI assistant for Quodom, a digital catalog and order builder.
Your task is to take a natural language request from a user and generate a list of product selections from our catalog, mapped to their exact product IDs and quantities, and a descriptive title for this selection.

Here is the current catalog of products in our database:
${catalogString}

You MUST follow these rules strictly:
1. Match the user's request to the most relevant products from the catalog.
2. Return a valid JSON object matching this schema exactly:
{
  "title": "A descriptive title for this Quodom selection (IA)",
  "items": [
    {
      "productId": <number representing the exact ID of the product from the catalog>,
      "quantity": <number representing the quantity of this product, must be a positive integer or float>
    }
  ]
}
3. ONLY return the JSON object. Do not wrap in markdown blocks, do not add explanations. Return ONLY valid, parseable JSON.
4. If a product the user asks for is not in the catalog, do not include it. Only output productIds that exist in the catalog list above.
5. The title should end with " (IA)" to indicate it was generated by AI.`;

    let responseText = '';
    const nativeFetch = (globalThis as any).fetch || (global as any).fetch;
    if (!nativeFetch) {
      throw new Error('Native fetch is not available in this Node.js environment');
    }

    if (geminiApiKey && geminiApiKey.trim() !== '') {
      // Call Gemini API (using gemini-2.5-flash as default)
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiApiKey}`;
      const response = await nativeFetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [{ text: `User request: "${prompt}"` }]
            }
          ],
          systemInstruction: {
            parts: [{ text: systemPrompt }]
          },
          generationConfig: {
            responseMimeType: 'application/json',
          }
        })
      });

      if (!response.ok) {
        throw new Error(`Gemini API returned status ${response.status}: ${await response.text()}`);
      }

      const data = await response.json() as any;
      responseText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
    } else {
      // Call OpenAI API
      const url = 'https://api.openai.com/v1/chat/completions';
      const response = await nativeFetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${openaiApiKey}`
        },
        body: JSON.stringify({
          model: 'gpt-4o-mini',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: prompt }
          ],
          response_format: { type: 'json_object' }
        })
      });

      if (!response.ok) {
        throw new Error(`OpenAI API returned status ${response.status}: ${await response.text()}`);
      }

      const data = await response.json() as any;
      responseText = data.choices?.[0]?.message?.content || '';
    }

    if (!responseText) {
      throw new Error('LLM returned an empty response');
    }

    // 3. Clean and parse JSON
    const parsed = cleanAndParseJson(responseText);

    // 4. Filter invalid product IDs
    const filteredItems = parsed.items.filter(item => validProductIds.has(item.productId));

    if (filteredItems.length === 0) {
      throw new Error('No items matched catalog product IDs');
    }

    return {
      title: parsed.title,
      items: filteredItems
    };

  } catch (error) {
    console.error('AI generation failed, falling back to mock generator. Error:', error);
    return generateMockQuodom(prompt);
  }
}

function cleanAndParseJson(text: string): GeneratedQuodom {
  let cleaned = text.trim();
  
  // Remove markdown code blocks if present
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.substring(7);
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.substring(3);
  }
  if (cleaned.endsWith('```')) {
    cleaned = cleaned.substring(0, cleaned.length - 3);
  }
  cleaned = cleaned.trim();
  
  const parsed = JSON.parse(cleaned);
  
  if (!parsed || typeof parsed !== 'object') {
    throw new Error('Parsed result is not an object');
  }
  
  if (typeof parsed.title !== 'string' || !Array.isArray(parsed.items)) {
    throw new Error('Parsed result is missing title or items');
  }
  
  const validatedItems: Array<{ productId: number; quantity: number }> = [];
  for (const item of parsed.items) {
    if (
      item &&
      item.productId !== undefined &&
      item.productId !== null &&
      !isNaN(Number(item.productId)) &&
      item.quantity !== undefined &&
      item.quantity !== null &&
      !isNaN(Number(item.quantity)) &&
      Number(item.quantity) > 0
    ) {
      validatedItems.push({
        productId: Number(item.productId),
        quantity: Number(item.quantity)
      });
    }
  }
  
  if (validatedItems.length === 0) {
    throw new Error('No valid items found in parsed response');
  }
  
  return {
    title: parsed.title,
    items: validatedItems
  };
}

async function generateMockQuodom(prompt: string): Promise<GeneratedQuodom> {
  const promptLower = prompt.toLowerCase();
  let keywordsToSearch: string[] = [];
  let categoryLabel = 'Generado';

  if (
    /\bpint(ar|ura|ando)?\b/i.test(promptLower) ||
    promptLower.includes('látex') ||
    promptLower.includes('latex') ||
    promptLower.includes('rodillo') ||
    promptLower.includes('pincel') ||
    promptLower.includes('pared') ||
    promptLower.includes('paredes')
  ) {
    keywordsToSearch = ['látex', 'latex', 'rodillo', 'pincel', 'esmalte', 'pintura', 'enduido', 'fijador', 'aguarrás', 'lija'];
    categoryLabel = 'Pintura';
  } else if (
    /\bbebid(a|as)?\b/i.test(promptLower) ||
    promptLower.includes('gaseosa') ||
    promptLower.includes('cerveza') ||
    promptLower.includes('cervezas') ||
    promptLower.includes('fernet') ||
    promptLower.includes('soda') ||
    promptLower.includes('agua') ||
    promptLower.includes('coca')
  ) {
    keywordsToSearch = ['gaseosa', 'cerveza', 'agua', 'fernet', 'jugo', 'soda', 'bebida', 'cola'];
    categoryLabel = 'Bebidas';
  } else if (
    /\bconstruc/i.test(promptLower) ||
    promptLower.includes('cemento') ||
    promptLower.includes('arena') ||
    promptLower.includes('cal') ||
    promptLower.includes('ladrillo') ||
    promptLower.includes('ladrillos') ||
    promptLower.includes('hierro') ||
    promptLower.includes('viga') ||
    promptLower.includes('obra')
  ) {
    keywordsToSearch = ['cemento', 'arena', 'cal', 'ladrillo', 'hierro', 'viga', 'piedra', 'adhesivo', 'cerecita', 'mezcla'];
    categoryLabel = 'Construcción';
  } else {
    // General keyword extraction
    const stopWords = new Set([
      'para', 'con', 'del', 'una', 'los', 'las', 'una', 'uno', 'unos', 'unas', 
      'este', 'esta', 'estos', 'estas', 'como', 'pero', 'por', 'the', 'and', 
      'for', 'with', 'this', 'that', 'paint', 'need', 'quiero', 'necesito', 
      'buscar', 'comprar', 'hacer', 'quodom', 'generar', 'crear', 'tengo'
    ]);
    const tokens = promptLower
      .split(/[^a-z0-9áéíóúüñ]/i)
      .map(t => t.trim())
      .filter(t => t.length >= 3 && !stopWords.has(t));
    keywordsToSearch = tokens;
  }

  let matchedProducts: any[] = [];
  if (keywordsToSearch.length > 0) {
    matchedProducts = await prisma.product.findMany({
      where: {
        OR: keywordsToSearch.map(kw => ({
          OR: [
            { name: { contains: kw } },
            { description: { contains: kw } }
          ]
        }))
      },
      take: 10
    });
  }

  // If no products match or keywords empty, return a default set of products from the DB
  if (matchedProducts.length === 0) {
    matchedProducts = await prisma.product.findMany({
      take: 5
    });
  }

  const items = matchedProducts.map(p => {
    let quantity = 1;
    const nameLower = p.name.toLowerCase();
    if (nameLower.includes('ladrillo')) {
      quantity = 100;
    } else if (nameLower.includes('cemento') || nameLower.includes('cal') || nameLower.includes('arena')) {
      quantity = 5;
    } else if (nameLower.includes('cerveza') || nameLower.includes('gaseosa') || nameLower.includes('bebida') || nameLower.includes('cola')) {
      quantity = 6;
    } else if (p.unit.toLowerCase().includes('litro') || p.unit.toLowerCase().includes('lts')) {
      quantity = 4;
    }
    return {
      productId: p.id,
      quantity
    };
  });

  let titlePrefix = prompt.length > 25 ? prompt.substring(0, 25).trim() + '...' : prompt.trim();
  titlePrefix = titlePrefix.charAt(0).toUpperCase() + titlePrefix.slice(1);
  const title = `${titlePrefix} (${categoryLabel} IA)`;

  return {
    title,
    items
  };
}
